### ISSUE TITLE
Use cosm-tome as the underlying cosmos client library

### ISSUE THREAD

**Issue by de-husk** [de-husk/cosmos-gas-profiler#64]
Once it is ready, cosm-orc will be the first user of [cosm-tome](https://github.com/de-husk/cosm-tome)

**Comment by 0xForerunner** [comment]
Hey @de-husk! Thanks for contributing this project. I was just about to suggest that a few of your files be split off into their own lib. I was gonna call it easy-cosmwasm or something along those lines. I was planning on using it in my own project.  The files that I'm thinking of in particular are key.rs, cosmos.rs, cosmwasm.rs and chain_res.rs. Together they could form a great little lib. Was that your intention with this issue that you created? What's your timeline for this? If you're not rushed would you mind if I went ahead and created the lib?

EDIT: I should have clicked that link before I posted! I see you're already well on your way to cleaning that all up! That's awesome thank you.

**Comment by de-husk** [comment]
Hey!, thanks for your interest.

I still have some work to do before cosm-tome is stable, but the cosmwasm API will be ready to use soon if you dont mind some potential choppy upgrades as the non-cosmwasm API interfaces get built out.

**Comment by de-husk** [comment]
As far as a timeline, I dont have dates but Im working on cosm-tome for most of next week. 

Longer term, cosm-orc will remain for integration testing and gas profiling cosmwasm contracts, and cosm-tome will be there for a high level, streamlined cosmos SDK.
